CentralManagement/Areas/Franchise/Controllers/SettingController.cs
using System;
using System.Web.Mvc;
using Drs.Infrastructure.JqGrid.Model;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Model.Franchise;
using Drs.Repository.Entities.Metadata;
using Drs.Repository.Log;
using Drs.Repository.Order;
using Drs.Repository.Shared;
using Drs.Service.Franchise;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using ResShared = CentralManagement.Resources.ResShared;

namespace CentralManagement.Areas.Franchise.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER + ", " + RoleConstants.INSTALLER)]
    public class SettingController : Controller
    {
        // GET: Franchise/Setting
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(JqGridFilterModel opts)
        {
            using (var repository = new GenericRepository<Drs.Repository.Entities.Franchise>())
            {
                var result = repository.JqGridFindBy(opts, FranchiseInfoJson.Key, FranchiseInfoJson.Columns, (e => e.IsObsolete == false)
                    , FranchiseInfoJson.DynamicToDto);
                return Json(result);
            }
        }


        public ActionResult Upsert(int? id)
        {
            FranchiseUpModel model = null;
            try
            {
                using (var repository = new FranchiseRepository())
                {
                    if (id.HasValue)
                    {
                        model = repository.FindModelById(id.Value);
                        ViewBag.Resource = JsonConvert.SerializeObject(model.Resource);
                    }
                    else
                    {
                        model = new FranchiseUpModel
                        {
                            FranchiseId = EntityConstants.NULL_VALUE
                        };
                    }

                    ViewBag.Model = JsonConvert.SerializeObject(model);

                }

                ViewBag.PropertyFile = "Resource";
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult DoUpsert(FranchiseUpModel model)
        {

            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }

                using (var service = new FranchiseSettingService())
                {
                    var response = service.ValidateModel(model);

                    if (response.HasError)
                    {
                        response.Title = ResShared.TITLE_REGISTER_FAILED;
                        return Json(response);
                    }

                    model.UserInsUpId = User.Identity.GetUserId();
                    response = service.Save(model);

                    if (response.HasError)
                        response.Title = ResShared.TITLE_REGISTER_FAILED;
                    
                    return Json(response);
                }
            }
            catch (Exception ex)
            {

                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult DoObsolete(int id)
        {
            try
            {
                var response = new ResponseMessageModel();

                using (var service = new FranchiseSettingService())
                {
                    service.DoObsolete(id, User.Identity.GetUserId(), response);
                }

                if (response.HasError)
                    response.Title = ResShared.TITLE_OBSOLETE_FAILED;

                return Json(response);
                //}
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

    }
}

CentralManagement/Areas/Franchise/Controllers/SyncController.cs
using System;
using System.Threading;
using System.Web.Mvc;
using Drs.Infrastructure.JqGrid.Model;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Repository.Entities.Metadata;
using Drs.Repository.Log;
using Drs.Repository.Shared;
using Drs.Service.Franchise;
using Microsoft.AspNet.Identity;
using ResShared = CentralManagement.Resources.ResShared;

namespace CentralManagement.Areas.Franchise.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER + ", " + RoleConstants.INSTALLER)]
    public class SyncController : Controller
    {
        // GET: Franchise/Sync
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult List(JqGridFilterModel opts)
        {
            using (var repository = new GenericRepository<Drs.Repository.Entities.Franchise>())
            {
                var result = repository.JqGridFindBy(opts, FranchiseInfoJson.Key, FranchiseInfoJson.Columns, (e => e.IsObsolete == false)
                    , FranchiseInfoJson.DynamicToDto);
                return Json(result);
            }
        }


        public ActionResult VersionList(JqGridFilterModel opts, int id)
        {
            using (var repository = new GenericRepository<Drs.Repository.Entities.FranchiseDataVersion>())
            {
                var result = repository.JqGridFindBy(opts, FranchiseDataVersionInfoJson.Key, FranchiseDataVersionInfoJson.Columns, (e => e.IsObsolete == false && e.FranchiseId == id)
                    , FranchiseDataVersionInfoJson.DynamicToDto);
                return Json(result);
            }
        }


        [HttpPost]
        public ActionResult DoVersion(int franchiseId)
        {

            try
            {
                using (var service = new FranchiseSettingService())
                {
                    var response = new ResponseMessageModel();
                    service.CreateNewVersion(franchiseId, response, User.Identity.GetUserId());
                    return Json(response);
                }
            }
            catch (Exception ex)
            {

                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult DoObsolete(int id)
        {
            try
            {
                var response = new ResponseMessageModel();

                using (var service = new FranchiseSettingService())
                {
                    service.DoObsoleteVersion(id, User.Identity.GetUserId(), response);
                }

                if (response.HasError)
                    response.Title = ResShared.TITLE_OBSOLETE_FAILED;

                return Json(response);
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }


    }
}

CentralManagement/Areas/Store/Controllers/SettingController.cs
using System;
using System.Web.Mvc;
using Drs.Infrastructure.JqGrid.Model;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Model.Settings;
using Drs.Model.Store;
using Drs.Repository.Account;
using Drs.Repository.Entities;
using Drs.Repository.Entities.Metadata;
using Drs.Repository.Log;
using Drs.Repository.Shared;
using Drs.Repository.Store;
using Drs.Service.Factory;
using Drs.Service.Store;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using ResShared = CentralManagement.Resources.ResShared;

namespace CentralManagement.Areas.Store.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER + ", " + RoleConstants.INSTALLER)]
    public class SettingController : Controller
    {
        // GET: Store/Setting
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(JqGridFilterModel opts)
        {
            using (var repository = new GenericRepository<ViewStoreInfo>())
            {
                var result = repository.JqGridFindBy(opts, StoreInfoJson.Key, StoreInfoJson.Columns, (e => e.IsObsolete == false)
                    , StoreInfoJson.DynamicToDto);
                return Json(result);
            }
        }


        public ActionResult Upsert(int? id)
        {
            StoreUpModel model = null;
            try
            {
                using (var repository = new StoreRepository())
                {
                    if (id.HasValue)
                    {

                        model = repository.FindModelById(id.Value);

                    }
                    else
                    {
                        model = new StoreUpModel
                        {
                            FranchiseStoreId = EntityConstants.NULL_VALUE
                        };
                    }
                    ViewBag.LstFranchises = JsonConvert.SerializeObject(repository.GetFranchises());
                    ViewBag.LastRegion = FactoryAddress.GetRegionChildByZipCode();
                    ViewBag.RegionsEnabled = JsonConvert.SerializeObject(FactoryAddress.GetAddressHierarchyOrderById());
                    ViewBag.RegionLang = JsonConvert.SerializeObject(SettingsData.Constants.AddressUpsertSetting);
                    ViewBag.ManagerStoreUsers = JsonConvert.SerializeObject(new AccountRepository(repository.Db).GetManagerStoreUsers());
                    ViewBag.Address = JsonConvert.SerializeObject(model.Address);
                    model.Address = null;
                    ViewBag.Model = JsonConvert.SerializeObject(model);
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult DoUpsert(StoreUpModel model)
        {

            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }

                using (var service = new StoreSettingService())
                {
                    var response = service.ValidateModel(model);

                    if (response.HasError)
                    {
                        response.Title = ResShared.TITLE_REGISTER_FAILED;
                        return Json(response);
                    }

                    model.UserInsUpId = User.Identity.GetUserId();
                    response = service.Save(model);

                    if (response.HasError)
                        response.Title = ResShared.TITLE_REGISTER_FAILED;
                    
                    return Json(response);
                }
            }
            catch (Exception ex)
            {

                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult DoObsolete(int id)
        {
            try
            {
                var response = new ResponseMessageModel();

                using (var service = new StoreSettingService())
                {
                    service.DoObsoleteStore(id, User.Identity.GetUserId(), response);
                }

                if (response.HasError)
                    response.Title = ResShared.TITLE_OBSOLETE_FAILED;

                return Json(response);
                //}
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_OBSOLETE_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

    }
}

CentralManagement/Areas/Terminal/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Drs.Infrastructure.JqGrid.Model;
using Drs.Infrastructure.Model;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Model.Franchise;
using Drs.Repository.Account;
using Drs.Repository.Log;
using Drs.Repository.Order;
using Drs.Service.Account;
using Drs.Service.Franchise;
using ResShared = CentralManagement.Resources.ResShared;

namespace CentralManagement.Areas.Terminal.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER + ", " + RoleConstants.INSTALLER)]
    public class SettingController : Controller
    {
        // GET: Terminal/Setting
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult List(JqGridFilterModel opts)
        {
            var devices = new AccountService().GetLstClients();

            if(devices.LstClients == null)
                devices.LstClients = new List<ConnectionFullModel>();

            var result = new
            {
                page = 1,
                records = devices.LstClients.Count,
                total = 1,
                rows = devices.LstClients.Select(e => new
                {
                    id = e.DeviceId,
                    cell = new
                    {
                        id = e.DeviceId,
                        Name = e.DeviceName,
                        e.StartDateTx,
                        e.EndDateTx,
                        e.Code
                    }
                })
            };

            return Json(result);
        }

        public ActionResult Upsert(int id)
        {
            try
            {
                var jSer = new JavaScriptSerializer();
                using (var repository = new FranchiseRepository())
                {
                    IAccountService accountService = new AccountService(new AccountRepository(repository.Db));
                    ViewBag.Model = jSer.Serialize(accountService.GetTerminalInfo(id, jSer));
                    ViewBag.LstFranchises = jSer.Serialize(new FranchiseService(repository).LstFranchise());
                    ViewBag.LstTerminalFranchise = jSer.Serialize(accountService.GetLstTerminalFranchise(id));
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex, id);
            }
            return View(String.Empty);
        }

        public ActionResult DoUpsert(TerminaFranchiseModel model)
        {
            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }

                return Json(new ResponseMessageModel
                {
                    HasError = false,
                    //Data = new AccountService().UpsertTerminalFranchise(model)
                });
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Message = "Error al momento de guardar la información: " + ex.Message,
                    Title = ResShared.TITLE_REGISTER_FAILED

                });
            }
        }
    }
}

CentralManagement/Areas/Terminal/Views/Setting/Index.cshtml
<div class="wrapper wrapper-content  animated fadeInRight" id="angJsjqGridId" ng-controller="modalDlgController">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Terminales del Call Center</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="jqGrid_wrapper">
                        <table id="GridId"></table>
                        <div id="GridPager"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blocker" ng-show="working">
        <div>
            Procesando...<img src="~/Content/img/ajax_loader.gif" alt="" />
        </div>
    </div>
</div>

@section css{
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/Content/ui-bootstrap-csp.css" rel="stylesheet" />
    <link href="~/Content/plugins/jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet" />
    <link href="~/Content/plugins/chosen/chosen.css" rel="stylesheet" />
    <link href="~/Content/plugins/iCheck/custom.css" rel="stylesheet">
}

@section scripts{
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/plugins/jqGrid/i18n/grid.locale-es.js"></script>
    <script src="~/Scripts/js/plugins/jqGrid/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/app/shared/upsertCtrl.js"></script>
    <script src="~/Scripts/app/shared/modalDlgCtrl.js"></script>
    <script src="~/Scripts/app/shared/hiddenDrct.js"></script>
    <script src="~/Scripts/app/ctrl/terminalCtrl.js"></script>
    <script src="~/Scripts/js/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/js/plugins/chosen/chosen.jquery.js"></script>
    <script src="~/Scripts/js/plugins/iCheck/icheck.min.js"></script>


<script type="text/javascript" language="javascript">
    $(document).ready(function () {

                @*window.upsert = function (franchiseId, gridId) {
            window.showConfirmServiceWithMsg({ franchiseId: franchiseId },
                { Title: 'Sincronizar archivos', Message: "¿Desea crear una nueva versión de los archivos para esta franquicia?", Type: 'info' }, "#angJsjqGridId",
                "@Url.Action("DoVersion", "Sync", new { area = "Franchise" })", gridId);
        };
            

        window.obsolete = function (id, gridId) {
            window.showObsolete(id, "#angJsjqGridId", "@Url.Action("DoObsolete", "Sync", new {area = "Franchise"})", gridId);
        };*@


        jQuery("#GridId").jqGrid({
            url: '@Url.Action("List", "Setting", new {area = "Franchise"})',
            datatype: "json",
            mtype: 'POST',
            colNames: ['ID', 'Terminal', 'Estatus', '¿Licencia?', 'Fecha inicial', 'Fecha final'],
            colModel: [
                { name: 'TerminalId', index: 'TerminalId', hidden: true },
                { name: 'Name', index: 'Name', width: 220, align: "center", sorttype: 'string', searchoptions: { sopt: ['bw'] } },
                { name: 'Code', index: 'Code', width: 110, align: "center", sorttype: 'string', search: false },
                { name: 'Code', index: 'Code', width: 110, align: "center", sorttype: 'string', search: false },
                { name: 'IsValid', index: 'IsValid', width: 80, align: "center", sorttype: 'string', search: false },
                { name: 'IsValid', index: 'UserNameIns', width: 160, align: "center", sorttype: 'string', sortable: false, search: false }
            ],
            rowNum: 10,
            rowList: [10, 30, 60],
            pager: '#GridPager',
            sortname: 'FranchiseId',
            height: 450,
            viewrecords: true,
            autowidth: true,
            shrinkToFit: true,
            sortorder: "desc",
            caption: "",
            add: true,
            edit: false,
            addtext: 'Agregar',
            altRows: true,
            hidegrid: false,
            subGridOptions: {
                plusicon: "glyphicon glyphicon-chevron-down position-relative",
                minusicon: "glyphicon glyphicon-chevron-right position-relative",
                reloadOnExpand: false,
                selectOnExpand: true
            },
            subGrid: true,
            subGridRowExpanded: function (subgridId, rowId) {
                var subgridTableId, pagerId;
                subgridTableId = subgridId + "_t";
                pagerId = "p_" + subgridTableId;
                $("#" + subgridId).html("<table id='" + subgridTableId + "' class='scroll'></table><div id='" + pagerId + "' class='scroll'></div>");
                $("#" + subgridTableId).jqGrid({
                    url: '@Url.Action("VersionList", "Sync", new {area = "Franchise"})?id=' + rowId,
                    datatype: "json",
                    mtype: 'POST',
                    colNames: ['ID', 'Versión', 'Creación (Fecha/Hora)', 'Usuario', 'Número total archivos', 'Total archivos descargados', '¿Completado?', 'Completado (Fecha/Hora)', 'Acción'],
                    colModel: [
                        { name: 'FranchiseDataVersionId', index: 'FranchiseDataVersionId', hidden: true },
                        { name: 'Version', index: 'Version', width: 170, align: "center", sorttype: 'string', search: false },
                        { name: 'Timestamp', index: 'Timestamp', width: 200, align: "center", sorttype: 'string', search: false },
                        { name: 'UserName', index: 'UserName', width: 160, align: "center", sorttype: 'string', sortable: false, search: false },
                        { name: 'TotalNumberOfFiles', index: 'TotalNumberOfFiles', width: 200, align: "center", sorttype: 'string', search: false },
                        { name: 'NumberOfFilesDownloaded', index: 'NumberOfFilesDownloaded', width: 200, align: "center", sorttype: 'string', search: false },
                        { name: 'IsCompleted', index: 'IsCompleted', width: 120, align: "center", sorttype: 'string', search: false },
                        { name: 'TimestampComplete', index: 'TimestampComplete', width: 200, align: "center", sorttype: 'string', search: false },
                        { name: 'Action', width: 100, align: "center", sortable: false, search: false }
                    ],
                    rowNum: 10,
                    pager: pagerId,
                    sortname: 'FranchiseDataVersionId',
                    sortorder: "asc",
                    height: 150,
                    gridComplete: function () {
                        var ids = $(this).jqGrid('getDataIDs');
                        for (var i = 0; i < ids.length; i++) {
                            var cl = ids[i];
                            var be = "";

                            be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Eliminar sincronización\" onclick=\"window.obsolete('" + cl + "', '#" + subgridTableId + "');\"><i class=\"fa fa-times icon-grid-st red\"></i></a>  ";

                            $(this).jqGrid('setRowData', ids[i], { Action: be });

                        }
                    }
                });
                $("#" + subgridTableId).jqGrid('navGrid', "#" + pagerId, { edit: false, add: true, addfunc: function () { window.upsert(rowId, "#" + subgridTableId); }, del: false, search: false, });
            }
        });

        jQuery("#GridId").jqGrid('navGrid', '#GridPager', {
            edit: false,
            add: false,
            refresh: true,
            del: false,
            search: false
        });

        jQuery("#GridId").jqGrid('filterToolbar', {
            stringResult: true,
            searchOperators: true,
            searchOnEnter: true,
            multipleSearch: true,
            ignoreCase: true
        });

        $(window).bind('resize', function () {
            var width = $('.jqGrid_wrapper').width();
            $('#GridId').setGridWidth(width);
        });
    });
</script>

}