CentralManagement/Areas/Report/Controllers/TopProductsController.cs
using System;
using System.Web.Mvc;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Model.Report;
using Drs.Repository.Log;
using Drs.Service.Report;

namespace CentralManagement.Areas.Report.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER)]
    public class TopProductsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchTopProductsByRangeDates(ReportRequestModel reportRequest)
        {
            var response = new ResponseMessageModel { HasError = false };

            try
            {
                IReportService reportService = new ReportService();
                response.Data = reportService.GetTopProductsByRangeDates(reportRequest.StartCalculatedDate, reportRequest.EndCalculatedDate);
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
                response.HasError = true;
            }

            return Json(response);
        }
    }
}

CentralManagement/Areas/Report/Views/TopProducts/Index.cshtml
<div class="wrapper wrapper-content  animated fadeInRight" id="angJsjqGridId" ng-controller="reportTimeSaleController">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Top 10 productos vendidos por sucursal</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-xs-8">
                            <div class="row">
                                <div class="col-xs-6">
                                    <label>
                                        Elige las fechas
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="input-daterange input-group" id="rangeDates">
                                        <span class="input-group-addon">Del&nbsp;&nbsp;</span>
                                        <input type="text" class="input-sm form-control" ng-model="m.startDate" name="start" />
                                        <span class="input-group-addon">&nbsp;&nbsp;al&nbsp;&nbsp;</span>
                                        <input type="text" class="input-sm form-control" ng-model="m.endDate" name="end" />
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <button class="btn btn-primary " ng-disabled="!m.startDate" ng-click="searchDaysByRange('@Url.Action("SearchTopProductsByRangeDates", "TopProducts", new { area = "Report" })')">
                                        <i class="fa fa-search-plus"></i> &nbsp;&nbsp;Buscar
                                    </button>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <div class="col-xs-12">
                                    <small>
                                        *Nota: Si sólo elige la fecha inicial se mostrará la información del día seleccionado
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-xs-12">
                            {{msgErr}}
                            <table class="table table-hover no-margins">
                                <thead>
                                    <tr>
                                        <th class="text-center"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Periodo</th>
                                        <th class="text-center">Franquicia</th>
                                        <th class="text-center">Sucursal</th>
                                        <th class="text-center">Posición</th>
                                        <th class="text-center">Producto </th>
                                        <th class="text-center"># de productos</th>
                                        <th class="text-center">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="r in lstResult" ng-class="setRowBinaryClass($index, lstResult, 'StoreName', 'rowColor', '', 'strip-row')">
                                        <td class="text-center"> {{r.Period}}</td>
                                        <td class="text-center">{{r.FranchiseName}}</td>
                                        <td class="text-center">{{r.StoreName}}</td>
                                        <td class="text-center">
                                            <span ng-class="'label label-' + setRowBinaryClass($index, lstResult, 'StoreName', 'rowLabel', 'info', 'primary')">
                                                <b>{{setPosition($index, lstResult, 'StoreName')}}</b>
                                            </span>
                                        </td>
                                        <td class="text-center font-bold">{{r.ProductName}}</td>
                                        <td class="text-center">{{r.Quantity}}</td>
                                        <td class="text-center">{{r.TotalByProduct}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blocker" ng-show="working">
        <div>
            Procesando...<img src="~/Content/img/ajax_loader.gif" alt="" />
        </div>
    </div>
</div>

@section css{
    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet" />
}

@section scripts{

    <script src="~/Scripts/js/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/app/ctrl/reportTimeSaleCtrl.js"></script>
    <script src="~/Scripts/app/shared/initDatePicker.js"></script>

}