CentralManagement/Areas/Store/Controllers/StoreNotificationController.cs
using System;
using System.Linq.Expressions;
using System.Web.Mvc;
using Drs.Infrastructure.JqGrid.Model;
using Drs.Infrastructure.Resources;
using Drs.Model.Constants;
using Drs.Model.Store;
using Drs.Repository.Entities;
using Drs.Repository.Entities.Metadata;
using Drs.Repository.Log;
using Drs.Repository.Notification;
using Drs.Repository.Shared;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using ResShared = CentralManagement.Resources.ResShared;

namespace CentralManagement.Areas.Store.Controllers
{
    [Authorize(Roles = RoleConstants.MANAGER + ", " + RoleConstants.STORE_MANAGER_ALL + ", " + RoleConstants.STORE_MANAGER)]
    public class StoreNotificationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(JqGridFilterModel opts)
        {
            Expression<Func<ViewStoreInfo, bool>> extraFilter;
            var userId = User.Identity.GetUserId();

            if (User.IsInRole(RoleConstants.STORE_MANAGER))
                extraFilter = (e => e.IsObsolete == false && e.ManagerUserId == userId);
            else
                extraFilter = (e => e.IsObsolete == false);


            using (var repository = new GenericRepository<ViewStoreInfo>())
            {
                var result = repository.JqGridFindBy(opts, StoreInfoJson.Key, StoreInfoJson.Columns, extraFilter
                    , StoreInfoJson.DynamicToDto);
                return Json(result);
            }
        }

        public ActionResult Upsert(int storeId)
        {
            try
            {
                using (var repository = new NotificationRepository())
                {
                    ViewBag.Model = JsonConvert.SerializeObject(new
                    {
                        Items = repository.GetNotifications(storeId),
                        CatMessages = repository.GetCatMessages(),
                        StoreName = repository.GetStoreName(storeId),
                        FranchiseStoreId = storeId
                    });
                }    
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
            }
            return View();
        }

        [HttpPost]
        public ActionResult DoUpsert(StoreNotificationModel model)
        {

            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }

                var userId = User.Identity.GetUserId();
                using (var repository = new NotificationRepository())
                {
                    using (var trans = repository.Db.Database.BeginTransaction())
                    {
                        var response = repository.InsertNotification(model, userId);
                        trans.Commit();
                        return Json(response);
                    }
                }

            }
            catch (Exception ex)
            {

                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult DoDelete(StoreNotificationModel model)
        {

            try
            {
                if (ModelState.IsValid == false)
                {
                    return Json(new ResponseMessageModel
                    {
                        HasError = true,
                        Title = ResShared.TITLE_REGISTER_FAILED,
                        Message = ResShared.ERROR_INVALID_MODEL
                    });
                }

                using (var repository = new NotificationRepository())
                {
                    using (var trans = repository.Db.Database.BeginTransaction())
                    {
                        var response = repository.DeleteNotification(model);
                        trans.Commit();
                        return Json(response);
                    }
                }

            }
            catch (Exception ex)
            {

                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = true,
                    Title = ResShared.TITLE_REGISTER_FAILED,
                    Message = ResShared.ERROR_UNKOWN
                });
            }
        }

        [HttpPost]
        public ActionResult Notifications(string notification, int limit)
        {
            try
            {
                using (var repository = new NotificationRepository())
                {
                    var data = repository.GetNotifications(notification, limit);
                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Data = data,
                    });
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = false,
                    Message = "Se presentó un problema al momento de consultar la información",
                });
            }
        }
    }
}

CentralManagement/Controllers/SharedController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Drs.Infrastructure.Resources;
using Drs.Repository.Entities;
using Drs.Repository.Log;
using Drs.Repository.Shared;
using Drs.Service.Factory;

namespace CentralManagement.Controllers
{
    [Authorize]
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
                throw;
            }
            
        }

        [HttpPost]
        public ActionResult ZipCodes(string code)
        {
            try
            {
                using (var repository = new CallCenterEntities())
                {
                    var data = FactoryAddress.GetQueryToExecByZipCode(repository, code, true).ToList();
                    return Json(new ResponseMessageModel
                    {
                        HasError = false,
                        Data = data,
                    });
                }
            }
            catch (Exception ex)
            {
                SharedLogger.LogError(ex);
                return Json(new ResponseMessageModel
                {
                    HasError = false,
                    Message = "Se presentó un problema al momento de consultar la información",
                });
            }
        }

    
     
        public ActionResult Resource(Guid? resource)
        {
            if(!resource.HasValue)
                return null;

            using (var repository = new ResourceRepository())
            {
                var originalFileName = repository.GetFileNameByStoreName(resource.Value);
                return String.IsNullOrEmpty(originalFileName) ? null : File(Path.Combine(FileUploadController.UploadFolder, resource.ToString()), MimeMapping.GetMimeMapping(originalFileName));
            }
        }


        public ActionResult Download(Guid resource)
        {
            using (var repository = new ResourceRepository())
            {
                var originalFileName = repository.GetFileNameByStoreName(resource);

                if (String.IsNullOrEmpty(originalFileName))
                    return null;

                Response.AppendHeader("Content-Disposition", "attachment; filename=\"" + originalFileName + "\"");
                return File(Path.Combine(FileUploadController.UploadFolder, resource.ToString()), "application/force-download;");
            }
        }
    }
}

CentralManagement/Areas/Store/Views/StoreNotification/Index.cshtml
<div class="wrapper wrapper-content  animated fadeInRight" id="angJsjqGridId" ng-controller="modalDlgController">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Sucursales del Call Center</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="jqGrid_wrapper">
                        <table id="GridId"></table>
                        <div id="GridPager"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="blocker" ng-show="working">
        <div>
            Procesando...<img src="~/Content/img/ajax_loader.gif" alt="" />
        </div>
    </div>
</div>

@section css{
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.min.css" rel="stylesheet" />
    <link href="~/Content/ui-bootstrap-csp.css" rel="stylesheet" />
    <link href="~/Content/plugins/jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <link href="~/Content/plugins/chosen/chosen.css" rel="stylesheet" />
    <link href="~/Content/plugins/iCheck/custom.css" rel="stylesheet">
}

@section scripts{
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/js/plugins/jqGrid/i18n/grid.locale-es.js"></script>
    <script src="~/Scripts/js/plugins/jqGrid/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/app/shared/upsertCtrl.js"></script>
    <script src="~/Scripts/app/shared/modalDlgCtrl.js"></script>
    <script src="~/Scripts/app/shared/hiddenDrct.js"></script>
    <script src="~/Scripts/app/ctrl/storeNotificationCtrl.js"></script>

    <script src="~/Scripts/angular-ui/ui-bootstrap.min.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>
    <script src="~/Scripts/js/jquery-ui-1.10.4.min.js"></script>
    <script src="~/Scripts/js/plugins/blueimp/jquery.fileupload.js"></script>
    <script src="~/Scripts/js/plugins/blueimp/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/app/shared/uploadFileCtrl.js"></script>
    <script src="~/Scripts/moment.min.js"></script>


    <script type="text/javascript" language="javascript">
        $(document).ready(function () {

            window.notifications = function (storeId) {
                window.showUpsertParams({ storeId: storeId }, "#angJsjqGridId", "@Url.Action("Upsert", "StoreNotification", new {area = "Store"})", "#GridId");
            };

            jQuery("#GridId").jqGrid({
                url: '@Url.Action("List", "StoreNotification", new { area = "Store" })',
                datatype: "json",
                mtype: 'POST',
                colNames: ['ID', 'Sucursal', 'Franquicia', 'Dirección', 'Gerente', 'Acci&oacute;n'],
                colModel: [
                    { name: 'FranchiseStoreId', index: 'FranchiseStoreId', hidden: true },
                    { name: 'Name', index: 'Name', width: 180, align: "center", sorttype: 'string', searchoptions: { sopt: ['bw'] } },
                    { name: 'FranchiseName', index: 'FranchiseName', width: 110, align: "center", sorttype: 'string', search: false },
                    { name: 'Address', index: 'Address', width: 200, align: "center", sorttype: 'string', search: false },
                    { name: 'ManagerUser', index: 'ManagerUser', width: 90, align: "center", sorttype: 'string', search: false },
                    { name: 'Action', width: 100, align: "center", sortable: false, search: false, formatter: window.actionFormatter }
                ],
                rowNum: 10,
                rowList: [10, 30, 60],
                pager: '#GridPager',
                sortname: 'FranchiseStoreId',
                height: 450,
                viewrecords: true,
                autowidth: true,
                shrinkToFit: true,
                sortorder: "desc",
                caption: "",
                add: false,
                edit: false,
                altRows: true,
                hidegrid: false,
                gridComplete: function () {
                    var ids = $(this).jqGrid('getDataIDs');
                    for (var i = 0; i < ids.length; i++) {
                        var cl = ids[i];
                        var be = "";
                        be += "<a href=\"javascript:;\" style=\"display:inline-block;\" title=\"Asignar notificaciones de la sucursal\" onclick=\"window.notifications('" + cl + "');\"><i class=\"fa fa-comments icon-grid-st blue-light\"></i></a>&nbsp;&nbsp;";
                        $(this).jqGrid('setRowData', ids[i], { Action: be });
                    }
                }
            });

            jQuery("#GridId").jqGrid('navGrid', '#GridPager', {
                edit: false,
                add: false,
                refresh: true,
                del: false,
                search: false
            });

            jQuery("#GridId").jqGrid('filterToolbar', {
                stringResult: true,
                searchOperators: true,
                searchOnEnter: true,
                multipleSearch: true,
                ignoreCase: true
            });

            $(window).bind('resize', function () {
                var width = $('.jqGrid_wrapper').width();
                $('#GridId').setGridWidth(width);
            });
        });
    </script>
}

CentralManagement/Areas/Store/Views/StoreNotification/Upsert.cshtml
@using Drs.Model.Settings
@{
    Layout = null;
}

<script>

    $(document).ready(function () {
        window.showModalFormDlg("#dlgUpModalId", "#FormId");
    });

</script>
<script src="~/Scripts/fileupload.js"></script>


<div class="modal inmodal" id="dlgUpModalId" tabindex="-1" ng-controller="upsertController" role="dialog" aria-hidden="true" ng-cloak>
    <div class="modal-dialog" style="width:960px" ng-controller="storeNotificationController">
        <div class="modal-content animated flipInY">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <i class="fa fa-comments modal-icon"></i>
                <h4 class="modal-title">Notificaciones de la sucursal al Call Center</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="ibox">
                            <div class="ibox-title navy-bg">
                                <h5>Notificaciones de la sucursal {{m.StoreName}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <form id="FormId" name="FormId" autocomplete="off" class="form-horizontal" role="form" ng-init='m = @(ViewBag.Model ?? "{}"); init();'>
                            @Html.AntiForgeryToken()
                            <input type="hidden" id="FranchiseStoreId" name="FranchiseStoreId" ng-model="m.FranchiseStoreId" ng-update-hidden />
                            <div class="row">
                                <div class="col-xs-8 col-xs-offset-2">
                                    <h3 class="element-center">{{m.StoreName}}</h3>
                                </div>
                            </div>
                            <div class="space-15"></div>
                            <div class="row">
                                <div class="col-xs-3">
                                    <div class="form-group">
                                        <label>Categoría</label>
                                        <select class="form-control" ng-options="c.Name for c in categories" ng-model="m.catSelected"></select>
                                    </div>
                                </div>
                                <div class="col-xs-4 col-xs-offset-1">
                                    <div class="form-group">
                                        <label>Notificación (Producto/Promoción/Mensaje)</label>
                                        <input type="text" class="form-control"
                                               ng-model="m.message"
                                               typeahead="notification as notification for notification in notifications($viewValue, '@Url.Action("Notifications", "StoreNotification", new { area = "Store" })')"
                                               placeholder='Ingresa la notificación'
                                               typeahead-editable="true"
                                               typeahead-loading="loadingData"
                                               typeahead-wait-ms="500"
                                               name="Notification"
                                               required="required"
                                               ng-maxlength="50" />
                                        <i ng-show="loadingData" class="glyphicon glyphicon-refresh"></i>
                                        <span><small>Mensajes en blanco comience con guión bajo "_", i.e., _1 </small></span><br />
                                        <span class="error" ng-show="FormId.Notification.$error.required">*Campo requerido</span>
                                        <span class="error" ng-show="FormId.Notification.$error.maxlength">*Longitud máxima de 50 caracteres</span>
                                    </div>
                                </div>
                                <div class="col-xs-3 col-xs-offset-1">
                                    <input type="checkbox" ng-model="m.isIndefinite" /> <label>&nbsp;Mostrar siempre</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-offset-4 col-xs-4">
                                    <input type="checkbox" ng-model="m.hasImage" /> <label>&nbsp;Agregar imagen a la notificación</label>
                                </div>
                            </div>
                            <div class="row" ng-show="m.hasImage">
                                <div class="col-xs-offset-2 col-xs-8">
                                    <input type="hidden" id="imageType" value="@SettingsData.Constants.FranchiseConst.SYNC_FILE_TYPE_IMAGE_NOTIFICATION" />
                                    @Html.Partial("~/Views/Shared/_UploadFile.cshtml")
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-4 col-xs-offset-4">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <button class="form-control btn btn-primary" ng-disabled="!FormId.Notification.$valid && (m.hasImage && m.resourceName)"
                                                ng-click="addNotification('@Url.Action("DoUpsert", "StoreNotification", new {area = "Store"})')" type="submit">
                                            Agregar
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <br />
                                    <div ng-show="MsgError" class="alert alert-danger element-center">
                                        {{MsgError}}
                                    </div>
                                </div>
                            </div>
                        </form>
                        <div class="row" ng-repeat="cat in categories" ng-show="cat.items.length > 0">
                            <div class="col-xs-offset-1 col-xs-10">
                                <div class="ibox-content">
                                    <label ng-style="{'color': 'white', 'background-color': cat.Color, 'padding' : '10px'}" class="control-label col-xs-12">
                                        {{cat.Name}}
                                    </label>

                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="col-xs-1">Acción</th>
                                                <th>Notificación</th>
                                                <th class="col-xs-3 element-center">Mostrar siempre</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat="itm in cat.items">
                                                <td style="text-align: center">
                                                    <button class="btn btn-warning btn-circle btn-tb"
                                                            ng-click="deleteNotification('@Url.Action("DoDelete", "StoreNotification", new {area = "Store"})',itm)"
                                                            title="Eliminar notificación" type="button">
                                                        <i class="fa fa-close"></i>
                                                    </button>
                                                </td>
                                                <td>
                                                    <div class="row" ng-show="itm.Resource">
                                                        <div class="col-xs-12">
                                                            <img ng-src="@Url.Action("Resource", "Shared", new { area = "" })?resource={{itm.Resource}}" width="64" height="64" />
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-xs-12">
                                                            {{itm.Message}}
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="element-center">{{(itm.IsIndefinite ? 'SI' : 'NO')}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-white" ng-click="cancel()">
                    Regresar
                </button>
            </div>
        </div>
        <div class="blocker" ng-show="working">
            <div>
                Procesando...<img src="~/Content/img/ajax_loader.gif" alt="" />
            </div>
        </div>
    </div>
</div>